khokha_food_review_system/foodiereviews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviewapp/', include('reviewapp.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('microsoft_authentication/', include('microsoft_authentication.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

khokha_food_review_system/reviewapp/urls.py
from django.urls import path

from . import views

app_name = 'reviewapp'
urlpatterns = [

    # ex: /reviewapp/
    path('', views.home, name='home'),

    # ex: /reviewapp/user_review
    path('user_review/', views.user_review, name='user_review'),

    # ex: /reviewapp/resto/5
    path('resto/<int:restaurant_id>/', views.details, name='details'),

    # ex: /reviewapp/resto/5/add
    path('resto/<int:restaurant_id>/add/', views.add, name='add'),

    # ex: /reviewapp/resto/5/reviewed
    path('resto/<int:restaurant_id>/reviewed/', views.reviewed, name='reviewed'),

    # ex: /reviewapp/api/comment/add/
    path('api/comment/add/', views.CommentAdd.as_view(), name="comment"),
    
    # ex: /reviewapp/api/reply/add/
    path('api/reply/add/', views.ReplyAdd.as_view(), name="reply"),

    # ex: /reviewapp/api/comment/add/
    path('api/like/add/', views.LikeAdd.as_view(), name="like"),

    # ex: /reviewapp/api/restaurants/list/
    path('api/restaurants/list/', views.GetRestaurantsByCategory.as_view(), name="restaurants_by_category"),

    # ex: /reviewapp/api/category_image
    path('api/category_image/', views.GetCategoryImage.as_view(), name="category_image"),

    # ex: /reviewapp/review/delete/
    path('review/delete/', views.ReviewDeleteView.as_view(), name='review_delete'),

    # ex/review/api/restaurant_image/
    path('api/restaurant_image/', views.GetRestaurantImage.as_view(), name='restaurant_image'),


    
]

khokha_food_review_system/reviewapp/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

import statistics


class Category(models.Model):
    category_text = models.CharField(max_length=50)
    category_img = models.ImageField(upload_to='category_images/', default='category_images/default.jpg')
    

    def get_restaurants(self):
        return self.restaurant_set


    def __str__(self):
        return self.category_text


class Restaurant(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    restaurant_text= models.CharField(max_length=100)
    restaurant_address= models.CharField(max_length=100)
    restaurant_img= models.ImageField(upload_to='restaurant_images/', default='restaurant_images/default.jpg')


    def __str__(self):
        return self.restaurant_text


    def review_amount(self):
        return self.review_set.count()
    
    
    def rating(self):
        if self.review_amount() is 0:
            return 0
        ratings = [r.review_rate for r in self.review_set.all()]
        avg_rate = round(statistics.mean(ratings))
        avg_rate = 1 if avg_rate is 0 else avg_rate
        return avg_rate
    
    
    def pricing(self):
        if self.review_amount() is 0:
            return 0
        prices = [r.review_price for r in self.review_set.all()]
        avg_price = round(statistics.mean(prices))
        avg_price = 1 if avg_price is 0 else avg_price
        return avg_price

class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    review_user = models.ForeignKey(User, on_delete=models.CASCADE)
    review_title = models.CharField(max_length=100)
    review_description = models.CharField(max_length=500)
    review_rate = models.IntegerField(default = 0)
    review_price = models.IntegerField(default = 0)
    review_date = models.DateTimeField(auto_now_add=True)
    review_images = models.ImageField(upload_to='review_images/',null=True, blank=True)

    def __str__(self):
        return self.review_description

    #function for getting all details of review by user 
    def get_review_by_user(self, user):
        # Filter reviews by the specified user
        user_reviews = Review.objects.filter(review_user=user)
        
        # Extract required details from the filtered reviews
        reviews_details = []
        for review in user_reviews:
            review_details = {
                'restaurant_name': review.restaurant.restaurant_text,
                'review_title': review.review_title,
                'review_description': review.review_description,
                'review_rate': review.review_rate,
                'review_price': review.review_price,
                'review_user_id': review.review_user.pk,
                'review_id': review.pk
            }
            reviews_details.append(review_details)
        
        return reviews_details






class Comment(models.Model):
    review = models.ForeignKey(Review,on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_description = models.CharField(max_length=500)


    def __str__(self):
        return self.comment_description



class Reply(models.Model):
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE)
    reply_user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply_description = models.CharField(max_length=500)


    def __str__(self):
        return self.reply_description



class Like(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        string = 'review: '+ str(self.review.pk) + 'user: ' + self.user.username
        return string

khokha_food_review_system/reviewapp/forms.py
from django.forms import ModelForm, Textarea
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'review_title',
            'review_description',
            'review_images',
        ]
        widgets = {
            'review_description': Textarea(attrs={'cols': 80, 'rows': 8}),
        }

khokha_food_review_system/reviewapp/views.py
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import HttpResponse
from microsoft_authentication.auth.auth_decorators import microsoft_login_required



def home(request):
    categories = Category.objects.all()
    return render(request, 'reviewapp/home.html', context={'categories': categories})


def user_review(request):
    user = request.user
    
    # Retrieve reviews associated with the current user
    reviews_details = Review().get_review_by_user(user)

    print(reviews_details)

    return render(request, 'reviewapp/user_review.html', context={'reviews': reviews_details})


def details(request, restaurant_id):
    restaurant = Restaurant.objects.filter(pk=restaurant_id).first()
    user_liked_reviews = []
    if request.user.is_authenticated:
        user_liked_reviews = get_liked_reviews_by_user_and_restaurant(request.user, restaurant)
    context = {
        'restaurant': restaurant, 
        'user': request.user, 
        'user_liked_reviews': user_liked_reviews
    }   
    return render(request, 'reviewapp/details.html', context)


def get_liked_reviews_by_user_and_restaurant(user, restaurant):
    liked_reviews = []
    for review in restaurant.review_set.all():
        like = review.like_set.filter(user=user).first()
        if like:
            liked_reviews.append(review.id)
    return liked_reviews



@microsoft_login_required()
def add(request, restaurant_id):
    form = ReviewForm()
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    context = {
        'restaurant': restaurant, 
        'form': form
    }
    return render(request, 'reviewapp/add.html', context)
    

@microsoft_login_required()
def reply(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment:
        comment.reply_set.create(reply_user=request.user, reply_description=request.POST.get('reply_description'))
    else:
        print("Invalid fields for reply. Required: comment id, username and reply description.")

    return render(request, 'reviewapp/details.html', {'restaurant': comment.review.restaurant, 'user': request.user})


# @login_required
# def reviewed(request, restaurant_id):
#     form = ReviewForm(request.POST)
#     # print(form)
#     if form.is_valid():
#         rtg = request.POST.get("rate", 1)
#         p = request.POST.get("price", 1)
#         res = get_object_or_404(Restaurant, pk=restaurant_id)
#         res.review_set.create(review_user=request.user, **form.cleaned_data, review_rate=rtg, review_price=p)
#     else:
#         print(form.errors)

#     return render(request, 'reviewapp/details.html', {'restaurant': res, 'user': request.user})

@microsoft_login_required()
def reviewed(request, restaurant_id):
    res = get_object_or_404(Restaurant, pk=restaurant_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)  # Include request.FILES for file uploads
        if form.is_valid():
            rtg = request.POST.get("rate", 1)
            p = request.POST.get("price", 1)
            review_instance = form.save(commit=False)
            review_instance.review_user = request.user
            review_instance.review_rate = rtg
            review_instance.review_price = p
            review_instance.restaurant = res
            review_instance.save()
            return redirect('reviewapp:details', restaurant_id=restaurant_id)
        else:
            print(form.errors)
    else:
        form = ReviewForm()
    return render(request, 'reviewapp/details.html', {'restaurant': res, 'user': request.user, 'form': form})



def comment_add(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if review:
        review.comment_set.create(comment_user=request.user, comment_description=request.POST.get('comment_description'))
    else:
        print("Invalid fields for comment. Required: review id, username and comment description.")

    return render(request, 'reviewapp/details.html', {'restaurant': review.restaurant, 'user': request.user})


class CommentAdd(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request, format=None):
        success = False
        new_comment_pk = None

        try:
            review_id = request.POST.get('review_id', None)
            comment_user_id = request.POST.get('comment_user_id', None)
            comment_description = request.POST.get('comment_description', None)

            if review_id and comment_user_id and comment_description:
                review = get_object_or_404(Review, pk=review_id)
                comment_user = get_object_or_404(User, pk=comment_user_id)
                new_comment = review.comment_set.create(comment_user=comment_user, comment_description=comment_description)
                success = True
                new_comment_pk = new_comment.pk
        except Exception as e:
            print(e, "Invalid fields for comment. Required: review id, username and comment description.")

        data = {
            'success': success,
            'new_comment_pk': new_comment_pk
        }
        return Response(data)


class ReplyAdd(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request, format=None):
        success = False
        new_reply_pk = None

        try:
            comment_id = request.POST.get('comment_id', None)
            reply_user_id = request.POST.get('reply_user_id', None)
            reply_description = request.POST.get('reply_description', None)

            if comment_id and reply_user_id and reply_description:
                comment = get_object_or_404(Comment, pk=comment_id)
                reply_user = get_object_or_404(User, pk=reply_user_id)
                new_reply = comment.reply_set.create(reply_user=reply_user, reply_description=reply_description)
                success = True
                new_reply_pk = new_reply.pk
        except Exception as e:
            print(e, "Invalid fields for reply. Required: comment id, username and reply description.")

        data = {
            'success': success,
            'new_reply_pk': new_reply_pk
        }
        return Response(data)


class LikeAdd(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request, format=None):

        success = False
        total_likes = None

        try:
            review_id = int(request.POST.get('review_id', None))
            user_id = int(request.POST.get('user_id', None))
        
            if review_id and user_id:
                review = get_object_or_404(Review, pk=review_id)
                print('got review!')
                user = get_object_or_404(User, pk=user_id)
                print('got user!')
                # check if user has liked before
                liked_before = review.like_set.filter(user=user).first()
                if liked_before:
                    print("User has already liked the review. A new like will not be created again.")
                else:
                    # try:
                    new_like = review.like_set.create(user=user)
                    success = True
                    # except Exception as e:
                    #     print(e, "Invalid fields for like. Required: review id, user_id.")
                    total_likes = review.like_set.count()
        except Exception as e:
            print(e, "Review id and user_id need to be integers.")

        data = {
                'success': success,
                'total_likes': total_likes
            }
        return Response(data)


# reviewapp/api/restaurants/list
class GetRestaurantsByCategory(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):

        restaurants = None

        try:
            category_id = request.GET.get('category_id', None)
            filter_id = request.GET.get('filter_id', None)
            print(filter_id, category_id)
            if category_id:
                # 0 = All categories
                if category_id == "0":
                    restaurants = list(Restaurant.objects.all().values())
                else:
                    category = get_object_or_404(Category, pk=category_id)
                    restaurants = list(category.restaurant_set.all().values())

                for r in restaurants:
                    restaurant = Restaurant.objects.filter(pk=r['id']).first()
                    
                    r['review_amount'] = restaurant.review_amount()
                    r['rating'] = restaurant.rating()
                    r['pricing'] = restaurant.pricing()
                    r['category'] = restaurant.category.category_text
                    r['image'] = restaurant.restaurant_img.url

                if filter_id == "0":
                    # just return the list of restaurants
                    pass

                elif filter_id == "1":
                    # Sort by rating
                    restaurants.sort(key=lambda x: int(x['rating']), reverse=False)
                elif filter_id == "2":
                    # Sort by review amount
                    restaurants.sort(key=lambda x: int(x['review_amount']), reverse=False)
                elif filter_id == "3":
                    # Sort by price
                    restaurants.sort(key=lambda x: int(x['pricing']), reverse=True)
                elif filter_id == "4":
                    # Default sort by rating
                    restaurants.sort(key=lambda x: int(x['pricing']), reverse=False)
        except Exception as e:
            print(e, "Invalid category id.")

khokha_food_review_system/reviewapp/templates/reviewapp/base.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Byte-Bite</title>

    <!--CSS-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reviewapp/style/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!--Font-->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <!--Font Awesome Icons-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
    <!-- JavaScript -->
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% load widget_tweaks %}

    <main>
        

        <nav class="navbar-foodie navbar navbar-expand-lg">
            <a class="navbar-brand" href="/reviewapp/">
                <img src="/static/reviewapp/images/frlogo3.png" height="100px" alt="foodie reviews">
            </a>
           <ul class="nav navbar-nav mr-auto nav-box-bar">
                <li class="nav-item"><a class="nav-link" href="{% url 'reviewapp:home' %}"><div class="nav-box">| Home |</a></li>
            </ul> 
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'reviewapp:user_review' %}">| View your Reviews |</a></li>
            </ul>
            <span class="navbar-text" style="margin-right:20px">Hello, {{user.username}}!</span>

            <form method="post" action="{% url 'microsoft_authentication:microsoft_authentication_logout' %}">
                {% csrf_token %}
                <button class="btn btn-info my-2 my-sm-0 login" style="font-weight: 500" type="submit">Log
                    out</button>
            </form>  
            {% else %}
            <a href="{% url 'microsoft_authentication:microsoft_authentication_login' %}"><button class="btn btn-outline-info my-2 my-sm-0 login">Login</button>
            </a>
            {% endif %}
        </nav>
        
        {% block content %}
        {% endblock %}
    </main>

    <style>
    .navbar{
        padding: 20px 100px;
        font-size: 1.3em;
        font-weight: bold;
        color:#333;
        background-color:white;
    }
    .nav-item{
        padding: 3px 40px;
    }
    </style>
</body>

</html>

khokha_food_review_system/reviewapp/templates/reviewapp/details.html
{% extends 'reviewapp/base.html' %}

{% block content %}

<div id="outer"  onchange="getRestaurants({{restaurant.pk}});"
style="width:100%; min-height: 100vh; background: no-repeat fixed center; background-size: cover;">

    <div class="content-container container">
        
        <!--RESTAURANT SUMMARY-->
        <div class="row">
            <div id="restaurant-summary" class="col card border-0 shadow mb-4">
                <div class="card-body">
                    
                    <!-- Back button -->
                    <a href="{% url 'reviewapp:home'%}" class="back-button">
                        <i class="fas fa-arrow-circle-left"></i>
                    </a>

                    <!-- Title -->
                    <h1><b>--- {{restaurant.restaurant_text}} ---</b></h1>
                    

                    <!-- Location -->
                    <label class="review-liner">
                        <span style="font-size: 1.5em;">
                            <i class="fas fa-map-marker-alt" style="color:cornflowerblue;" ></i>
                        </span>
                        <strong>{{ restaurant.restaurant_address }}</strong>
                    </label>

                    <!-- Category -->
                    <label class="review-liner">
                        <p><span class="badge badge-pill badge-primary category"><strong>{{ restaurant.category.category_text }}</strong></span></p>
                    </label>
                    
                    <!-- Average rating -->
                    <label class="review-liner">
                        <div class="rate">
                            {% for i in restaurant.rating|rjust:restaurant.rating %}
                            <i class="fas fa-star"/></i>
                            {% endfor %}
                        </div>
                    </label>

                    <!-- Average price -->
                    <label class="review-liner">
                        <div class="price">
                            {% for i in restaurant.pricing|rjust:restaurant.pricing %}
                            <i class="fas fa-rupee-sign"></i>
                            {% endfor %}
                        </div>
                    </label>
                    
                    <!-- Reviews count -->
                    <label class="review-liner">    
                        <strong>| {{ restaurant.review_set.count }} review(s) | </strong>
                    </label>
                </div>
            </div>        
        </div>
        
        <!--ADD REVIEW-->
        <a href="{% url 'reviewapp:add' restaurant.id %}" id="add-review" class="btn btn-lg btn-block">
            <strong>Add a Review!</strong>
        </a>

        <!--ALL REVIEWS-->
        
        {% if restaurant.review_set.all %}
            {% for review in restaurant.review_set.all|dictsortreversed:"pk" %}
                <div class="row">
                    <div class="col card" style="margin: 10px">
                        <div class="card-body">
                            <div class="user-bar">
                                <span class="user-icon"><i class="fas fa-user-circle"></i></span>
                                <div class="user-icon-side review-meta-data">
                                    <span><strong>{{review.review_user}}</strong></span><br>
                                    <span class="date">Reviewed on {{ review.review_date }}</span>
                                </div>
                            </div>
                            

                            <label class="review-liner-small review-icon">
                                {% for i in review.review_rate|rjust:review.review_rate %}
                                <i class="fas fa-star rate-small"/></i>
                                {% endfor %}
                            </label>
                            <label id="price" class="review-liner-small review-icon">
                                {% for i in review.review_price|rjust:review.review_price %}
                                <i class="fas fa-rupee-sign price-small"/></i>
                                {% endfor %}
                            </label>
                            
                            <h3>{{ review.review_title }}</h3>
                            {{review.review_description}}
                            <hr>
                            {% comment %} add the uploaded image {% endcomment %}
                            {% if review.review_images %}
                                <img src="{{ review.review_images.url }}" class="img-fluid" alt="Responsive image">
                            {% endif %}                            
                            <!--Likes-->
                            <div id="rl{{ review.id }}" class="row">
                                <div class="col-1">
                                    {% if review.id in user_liked_reviews %}
                                        <span class="badge badge-primary">Liked! </span>
                                    {% else %}
                                    <form action="#" method="post" onsubmit="addLike(this); return false;">
                                        {% csrf_token %}
                                        <input type="submit" value="Like" class="btn btn-outline-primary btn-sm" style="height:20px;line-height: 0px;"></input>
                                        <input type="hidden" name="review_id" value="{{ review.id }}" />
                                    </form>
                                    {% endif %}
                                </div>
                                <div class="col-1">
                                    <span class="badge badge-danger">
                                        <span class="likes-count" style="padding-right:10px;">{{review.like_set.count}}</span>
                                        <i class="fas fa-thumbs-up"></i>
                                    </span>
                                </div>
                            </div>
                            <hr>

                            <!-- COMMENTS -->
                            <div>
                                
                                <!-- ADD COMMENT -->
                                <div class="row row-comment-reply">
                                    <span class="user-icon-small col"><i class="fas fa-user-circle"></i></span>
                                    <form action="#" method="post" class="col-11 comment_form" onsubmit="addComment(this); return false;">
                                        {% csrf_token %}
                                        <input type="text" class="form-control new-comment-reply" name="comment_description" placeholder="Reply to this review..."> 
                                        <input type="hidden" name="review_id" value="{{ review.id }}" />
                                    </form>
                                </div>

                                <!-- CURRENT COMMENTS -->
                                <div id="rc{{ review.id }}">
                                    {% for comment in review.comment_set.all|dictsortreversed:"pk" %}
                                        <div>
                                            <div class="row row-comment-reply">
                                                <span class="user-icon-small col"><i class="fas fa-user-circle"></i></span>
                                                <div class="col-11">
                                                    <div class="comment-reply-content">
                                                        <span class="comment-reply-username">{{comment.comment_user}}</span>
                                                        <span class="comment-reply-description">{{comment.comment_description}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <!-- OPTIONS -->
                                            <div id="cc{{ comment.id }}" class="replies-with-comment-options">
                                                <div class="comment-options">
                                                    <a href="#" onclick="createAddReply({{ comment.id }}, this); return false;">Reply</a>
                                                </div>
                                            </div>

                                            <!-- CURRENT REPLIES -->
                                            <div id="c{{ comment.id }}" class="replies">
                                                {% for reply in comment.reply_set.all|dictsortreversed:"pk" %}
                                                    <div class="row row-comment-reply">
                                                        <span class="user-icon-small col"><i class="fas fa-user-circle"></i></span>
                                                        <div class="col-11">
                                                            <div class="comment-reply-content">
                                                                <span class="comment-reply-username">{{reply.reply_user}}</span>
                                                                <span class="comment-reply-description">{{reply.reply_description}}</span>
                                                            </div>  
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        {% else %}
            <div id="no-reviews-yet-message" class="alert alert-success" role="alert">
                <p>There are no reviews for {{ restaurant.restaurant_text }} yet.</p>
                <p>Would you like to start writing a review?</p>
            </div>
        {% endif %}
    </div>
</div>

<!--SAMPLE COMMENT REPLY LIKE-->
{% include 'reviewapp/components_restaurant_details.html' %}

<!--CSS & JS-->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'reviewapp/style/restaurantdetails.css' %}" />
{% load static %}
<script src="{% static "reviewapp/js/restaurant.comment.reply.like.js" %}"></script>

<script>
    var user_id = "{{ user.id }}";
    var user_username = "{{ user.username }}";
    

    $(document).ready(function() {
        getRestaurantImage({{ restaurant.pk }});
    });
    function getRestaurantImage(restaurantId) {
        var endpoint = "/reviewapp/api/restaurant_image/";
    
        $.ajax({
            method: "GET",
            url: endpoint,
            data: {
                restaurant_id: restaurantId,
            },
            success: function(data) {
                console.log(data);
                // Process the response data here
                var size = Object.keys(data).length;
                // Iterate through the categories object
                for (var i = 0; i < size; i++) {
                    // Check if the current category's ID matches the specified categoryId
                    if (data[i].id == restaurantId) {
                        console.log(data[i]);
                        
                        var imageURL = "url('/media/" + data[i].restaurant_img + "')";
                        console.log(imageURL);
                        $('#outer').css("background-image", imageURL); 
                        console.log(imageURL);
                        break; // Exit the loop once the category is found
                    }
                }
            },
            error: function(xhr, status, error) {
                console.error("Error fetching restaurant images:", error);
            }
        });
    }

</script>
{% endblock %}